services:
  - type: web
    name: car-poster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8080
      - key: GEMINI_API_KEY
        sync: false
      - key: USER
        sync: false
      - key: PASSWORD
        sync: false
      - key: PEXELS_API_KEY
        sync: false
